### PR TITLE
Added Coin, Added Gitgnore, Added gitattributes

### PR DESCRIPTION
**Pull request by HurricanKai**
Here you go, I hope it is ok for you that someone else wants to help you make this little game more fun :)
also i added an Gitgnore and an Gitattributes (which are just files for Git)

Also added Encryption for Coin & an Decrypiton

You can Generally use this!
Its Crypiton.Encrypt(string plainText, string passPhrase) and Cryption.Decrypt(string cipherText, string passPhrase)

passPhrase needs to be the Same to succsefull decrypt again!

### CODE REVIEW

**Review by Jeremi247 — COMMENTED** [review]
This is quite interesting and I may use that in the future. 
But I can not see any possible usage in this game, because I want it to be based each time on the new session, and I do not think that I would use those coins in any way.
Other things:
Why are you creating new random 3 times? 
And what's the point of all those random characters? Cause only the last line matters anyway. Is encryption also changing lines position or removes next line char?

**Comment by HurricanKai** [comment]
I encrypted the File (with Random Chars and the Encrypter) so you cannot cheat.
Also, the Encrypter is made to Encrypt String s not String[] s so i just run every line thorught it:

```
File.ReadAllLines(path); //Path is Defined
int x = 0;
Foreach(string line in lines)
{
lines[x] = Crypter.Encrypt(lines[x], pass); //Pass is also Defined
}
File.WriteAllLines(path, lines);
//There you go, ,same is then for decryption!

**Comment by HurricanKai** [comment]
hmm, Ok, Im also a learner in Games, and i just worked on the Coins for fun!

I also made an little Shop system (looks Horrible)
and "tryed" to understand your weapon system, i also tryed to make an Weapon class, which can register all weapons, so you dont have to do every mechanik * the amount of weapons, which works OK

i woud recommend reworking the hole Weapon System, it does not seem to work that good to me!

**Comment by Jeremi247** [comment]
Then all those lines that you are encrypting are highly redundant and their only purpose is to mislead potential cheater?
Weapon system was made in a hurry, I just wanted it to work :F. Most of the time that I spend on this project is reworking because I find better solutions :P

**Comment by HurricanKai** [comment]
Nice xD, have a look at my fork, im adding the Shop system now, (Its in the Dev branch because its containing some "Cheating buttons") also, Have a look at issues! I Found and Pritty bad Bug, (i dont know if this is also on your build, but at me it is!
Maybe you can help me with that

**Comment by HurricanKai** [comment]
Adding new Pull request when Shop Finished!

**Pull request closed without merging**
